import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class JobListingService {
  constructor() {}
  getJobs() {
    return [
      {
        id: 1,
        title: 'Front-End Developer',
        company: 'VOIS-Code',
        location: 'Cairo',
        type: 'Full time',
        posted: '3 mins ago',
        about: [
          'VOIS-Code is a forward-thinking technology company dedicated to crafting innovative software solutions tailored to meet the evolving needs of modern businesses.',
          'Located in Cairo, we specialize in building dynamic and responsive web applications, emphasizing scalability and user-centric designs.',
          'Our team thrives on collaboration, blending creativity with technical expertise to deliver exceptional front-end solutions.',
          'At VOIS-Code, we are passionate about pushing boundaries, staying ahead of industry trends, and fostering a work environment that inspires growth and innovation.',
        ],
        description:
          'Lead the development and implementation of front-end architecture for web applications.',
        jobDescriptionInfo:
          'Develop responsive and scalable user interfaces using modern JavaScript frameworks like Angular or React. Collaborate with cross-functional teams to create seamless UI/UX experiences.',
        salary: '$500/Hour',
        requirements: [
          'Bachelor’s degree in Computer Science or related field',
          '3+ years of front-end development experience',
          'Proficiency in JavaScript, HTML5, CSS3',
          'Experience with RESTful APIs and Git version control',
        ],
        preferredSkills: [
          'Experience with Angular, React, or Vue.js',
          'Knowledge of UI/UX design principles',
          'Familiarity with testing frameworks such as Jasmine or Mocha',
        ],
        productDesigner:
          'Working closely with the design team to create a cohesive user experience across multiple devices and screen sizes.',
        expirationDate: '2024-12-31',
        phone: '+20-123-456-7890',
        email: 'hr@vois-code.com',
        companyLogo: 'assets/images/Home/Company-1.jpg',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 2,
        title: 'Fresh (React Native) Developer',
        company: 'Capgemini',
        location: 'Canada',
        type: 'Full time',
        posted: '10 mins ago',
        about: [
          'Capgemini is a globally renowned leader in consulting, digital transformation, and technology services, committed to helping businesses unlock their potential through cutting-edge solutions.',
          'Operating in Canada, our expert teams specialize in developing cross-platform mobile applications using React Native, ensuring seamless performance on iOS and Android devices.',
          'By combining technical proficiency with a customer-first approach, we strive to create intuitive and high-performing applications.',
          'At Capgemini, innovation is at the core of our operations, supported by a strong culture of collaboration and excellence.',
        ],
        description:
          'Develop and build advanced applications,Review code developed by the rest of the team.',
        jobDescriptionInfo:
          'Develop cross-platform mobile applications using React Native. Ensure smooth performance across iOS and Android platforms. Collaborate with back-end developers to integrate APIs.',
        requirements: [
          'Bachelor’s degree in Software Engineering or related field',
          'Proficiency in JavaScript and React Native',
          'Knowledge of mobile design principles and mobile performance optimization',
        ],
        preferredSkills: [
          'Experience with Redux or MobX for state management',
          'Understanding of RESTful APIs and back-end integration',
          'Familiarity with Git and CI/CD tools',
        ],
        productDesigner:
          'Work with UI/UX teams to optimize user experiences on mobile devices.',
        expirationDate: '2025-01-15',
        phone: '+1-555-123-4567',
        email: 'jobs@capgemini.ca',
        salary: '$1000/Hour',
        companyLogo: 'assets/images/Home/Company-2.jpg',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 3,
        title: 'FullStack Senior Software Engineer (Ruby/JS-TS)',
        company: 'Procore Technologies',
        location: 'India',
        type: 'Full time',
        posted: '2 hours ago',
        about: [
          'Procore Technologies stands at the forefront of construction management software, empowering communities worldwide to build smarter and more efficiently.',
          'With a strong presence in India, we combine industry expertise with advanced technologies such as Ruby on Rails, JavaScript, and TypeScript to create scalable web applications.',
          'Our mission is to transform the way construction teams collaborate, offering tools that enhance productivity and decision-making.',
          'At Procore, we value innovation, teamwork, and a deep commitment to delivering products that make a meaningful impact on our clients and their projects.',
        ],
        description:
          'What if you could use your technology skills to develop a product that impacts the way communities’ hospitals.',
        jobDescriptionInfo:
          'Lead full-stack development projects using Ruby on Rails, JavaScript, and TypeScript. Work with cross-functional teams to deliver scalable web applications.',
        requirements: [
          '5+ years of full-stack development experience',
          'Proficiency in Ruby on Rails, JavaScript, and TypeScript',
          'Experience with relational databases (PostgreSQL, MySQL)',
          'Strong problem-solving and debugging skills',
        ],
        preferredSkills: [
          'Experience with cloud platforms like AWS or Azure',
          'Knowledge of Docker and Kubernetes',
          'Familiarity with front-end frameworks like Angular or React',
        ],
        productDesigner:
          'Collaborate with designers to ensure the best user experience and performance across web applications.',
        expirationDate: '2024-11-30',
        phone: '+91-98765-43210',
        email: 'careers@procoretech.com',
        salary: '$1200/Hour',
        companyLogo: 'assets/images/Home/Company-3.jpg',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 4,
        title: 'Junior Frontend Developer (Angular)',
        company: 'Emaratech',
        location: 'Cairo',
        type: 'Part time',
        posted: '3 mins ago',
        about: [
          'Emaratech is a leading provider of advanced technology solutions, dedicated to delivering superior digital services and software development to businesses worldwide.',
          'From our Cairo office, we focus on developing robust, responsive web applications powered by Angular, ensuring exceptional performance and user experiences.',
          'Our team is driven by a shared passion for technology and innovation, working closely with clients to understand their needs and deliver customized solutions.',
          'At Emaratech, we foster an environment of collaboration, continuous improvement, and creativity, enabling us to exceed expectations consistently.',
        ],
        description:
          'We are looking for Angular developers for our Egypt (Cairo ) office',

        jobDescriptionInfo:
          'Develop responsive web applications using Angular and collaborate with designers and backend developers.',
        requirements: [
          '1+ years of experience in frontend development',
          'Proficiency in HTML, CSS, and JavaScript',
          'Basic knowledge of Angular and TypeScript',
        ],
        preferredSkills: [
          'Familiarity with RESTful APIs',
          'Experience with version control systems like Git',
          'Knowledge of UI/UX design principles',
        ],
        productDesigner:
          'Work closely with designers to create user-friendly interfaces and optimize web applications for maximum speed and scalability.',
        expirationDate: '2024-11-01',
        phone: '+20-12345-67890',
        email: 'careers@emaratech.com',
        salary: '$230/Hour',
        companyLogo: 'assets/images/Home/Company-4.jpg',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 5,
        title: 'Fresh Backend (.Net)',
        company: 'Santionan',
        location: 'Cairo',
        type: 'Full time',
        posted: '3 sec ago',
        about: [
          'Santionan is a Cairo-based technology company dedicated to building powerful and efficient back-end systems using the latest .NET technologies.',
          'With a focus on scalability, reliability, and seamless integration, we provide tailored server-side solutions that address the unique challenges faced by businesses.',
          'Our team takes pride in fostering a collaborative environment, combining technical expertise with a customer-first mindset to deliver applications that drive success.',
          'At Santionan, we are committed to innovation, quality, and helping our clients achieve their goals through robust and scalable technology.',
        ],
        description:
          'We want someone who has good skilled with using and bulid .net application at server side.. ',
        jobDescriptionInfo:
          'Assist in developing and maintaining server-side applications using .NET technologies.',
        requirements: [
          'Familiarity with C# and ASP.NET',
          'Understanding of database management systems',
          'Ability to work in a team environment',
        ],
        preferredSkills: [
          'Experience with RESTful services',
          'Knowledge of Azure or AWS',
          'Understanding of Agile methodologies',
        ],
        productDesigner:
          'Collaborate with frontend developers to integrate user-facing elements with server-side logic.',
        expirationDate: '2024-11-10',
        phone: '+20-09876-54321',
        email: 'hr@santionan.com',
        salary: '$250/Hour',
        companyLogo: 'assets/images/Home/Company-5.jpg',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 6,
        title: 'Junior Web Developer (Remote)',
        company: 'Cocharge',
        location: 'Germany',
        type: 'Part time',
        posted: '20 mins ago',
        about: [
          'Cocharge is a Germany-based tech company specializing in developing remote-friendly software solutions.',
          'We focus on building innovative and user-friendly web applications to meet the needs of modern businesses.',
          'Our team values collaboration, creativity, and leveraging cutting-edge technologies to deliver exceptional results.',
          'At Cocharge, we emphasize a supportive work environment and prioritize both professional growth and work-life balance.',
        ],
        description:
          'We want someone who has been doing this for a solid 2-3 years...',
        jobDescriptionInfo:
          'Assist in the development of web applications and support the team in various projects.',
        requirements: [
          '1-3 years of experience in web development',
          'Proficiency in HTML, CSS, and JavaScript',
          'Experience with at least one frontend framework (React, Angular, etc.)',
        ],
        preferredSkills: [
          'Experience with backend technologies like Node.js',
          'Knowledge of responsive design techniques',
          'Familiarity with Git for version control',
        ],
        productDesigner:
          'Contribute to the design and development of user interfaces, ensuring an optimal user experience.',
        expirationDate: '2024-12-01',
        phone: '+49-12345-67890',
        email: 'jobs@cocharge.com',
        salary: '$300/Hour',
        companyLogo: 'assets/images/Home/Company-6.jpg',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 7,
        title: 'Senior React Native Developer',
        company: 'Gucci, Inc',
        location: 'New York, NY',
        type: 'Full time',
        posted: '1 sec ago',
        about: [
          'Gucci, Inc is a global luxury brand renowned for its innovative designs and exceptional craftsmanship.',
          'The New York-based tech division focuses on developing high-quality mobile applications to enhance customer engagement.',
          'Our team combines expertise in technology with a passion for delivering cutting-edge digital experiences.',
          'At Gucci, Inc, we value creativity, collaboration, and staying ahead of trends in both fashion and technology.',
        ],
        description:
          'Are you a budding web developer with a passion for creating stunning websites and web applications?',
        jobDescriptionInfo:
          'Lead the development of mobile applications using React Native and mentor junior developers.',
        requirements: [
          '3+ years of experience in mobile app development',
          'Strong knowledge of React Native and JavaScript',
          'Experience with RESTful APIs',
        ],
        preferredSkills: [
          'Familiarity with Redux for state management',
          'Knowledge of mobile app deployment processes',
          'Experience with UI/UX design principles',
        ],
        productDesigner:
          'Work with product managers and designers to create engaging mobile applications.',
        expirationDate: '2024-11-15',
        phone: '+1-23456-78900',
        email: 'careers@gucci.com',
        salary: '$600/Hour',
        companyLogo: 'assets/images/Home/Company-7.jpg',
        urgent: true,
        senior: true,
        fullTime: true,
      },
      {
        id: 8,
        title: 'SW QA Engineer - RVE',
        company: 'Siemens Software',
        location: 'Remote',
        type: 'Part time',
        posted: '3 hours ago',
        about: [
          'Siemens Software is a leader in engineering and technology solutions, helping industries innovate with advanced software tools.',
          'The remote QA team specializes in ensuring the reliability and quality of high-performance software applications.',
          'We pride ourselves on fostering a culture of excellence and precision in all aspects of software testing and validation.',
          'At Siemens, innovation, quality, and collaboration are the core pillars driving our success and customer satisfaction.',
        ],
        description:
          'Calibre’s high-capacity and high-performance tools are key to our customers’ .',
        jobDescriptionInfo:
          'Conduct testing and quality assurance for software products and report issues.',
        requirements: [
          '2+ years of experience in software testing',
          'Knowledge of automated testing tools',
          'Understanding of the software development life cycle',
        ],
        preferredSkills: [
          'Experience with Agile methodologies',
          'Familiarity with scripting languages like Python or JavaScript',
          'Strong analytical and problem-solving skills',
        ],
        productDesigner:
          'Collaborate with development teams to improve product quality and user satisfaction.',
        expirationDate: '2024-11-20',
        phone: '+1-34567-89012',
        email: 'jobs@siemens.com',
        salary: '$800/Hour',
        companyLogo: 'assets/images/Home/Company-8.jpg',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 9,
        title: 'Junior Front-End Developer',
        company: 'TechSphere',
        location: 'New York, USA',
        type: 'Full time',
        posted: '2 hours ago',
        about: [
          'TechSphere is a New York-based technology firm specializing in innovative software solutions for businesses.',
          'We focus on developing responsive web applications with exceptional design and performance.',
          'Our team fosters a dynamic and collaborative work environment, emphasizing continuous learning and innovation.',
          'At TechSphere, we are dedicated to creating impactful digital experiences that drive client success.',
        ],
        description:
          'Build and maintain responsive web pages using HTML, CSS, and JavaScript.',
        jobDescriptionInfo:
          'Collaborate with design and backend teams to create high-quality web applications.',
        requirements: [
          '1+ years of experience in frontend development',
          'Proficiency in HTML, CSS, and JavaScript',
          'Familiarity with frameworks like React or Angular',
        ],
        preferredSkills: [
          'Experience with RESTful APIs',
          'Knowledge of version control systems',
          'Strong problem-solving skills',
        ],
        productDesigner:
          'Help design and implement user-friendly interfaces that enhance user experience.',
        expirationDate: '2024-12-15',
        phone: '+1-45678-90123',
        email: 'jobs@techsphere.com',
        salary: '$55,000/year',
        companyLogo: 'assets/images/jobs/job-1.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 10,
        title: 'Junior Back-End Developer',
        company: 'CodeNexus Ltd',
        location: 'London, UK',
        type: 'Full time',
        posted: '10 hour ago',
        about: [
          'CodeNexus Ltd is a London-based technology company specializing in backend development for scalable systems.',
          'We deliver high-performance server-side solutions tailored to client requirements using cutting-edge tools.',
          'Our team values collaboration, innovation, and excellence in delivering robust and efficient applications.',
          'At CodeNexus, we focus on leveraging technology to empower businesses and achieve measurable success.',
        ],
        description:
          'Develop server-side logic and APIs using Node.js or Python.',
        jobDescriptionInfo:
          'Work with the development team to design and implement scalable backend systems.',
        requirements: [
          '1+ years of experience in backend development',
          'Proficiency in Node.js or Python',
          'Understanding of database technologies',
        ],
        preferredSkills: [
          'Familiarity with cloud services',
          'Knowledge of RESTful API design',
          'Strong communication skills',
        ],
        productDesigner:
          'Collaborate with frontend developers to integrate APIs and maintain data integrity.',
        expirationDate: '2024-12-20',
        phone: '+44-56789-01234',
        email: 'careers@codenexus.com',
        salary: '£40,000/year',
        companyLogo: 'assets/images/jobs/job-2.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 11,
        title: 'Junior UI/UX Designer',
        company: ' DesignWaves',
        location: 'Remote',
        type: 'Full time',
        posted: '2 sec ago',
        about: [
          'DesignWaves is a creative design agency focused on delivering top-notch UI/UX solutions for clients worldwide.',
          'We specialize in creating user-friendly and visually compelling designs for web and mobile platforms.',
          'Our team thrives on innovation, collaboration, and a deep understanding of user behavior and needs.',
          'At DesignWaves, we aim to provide impactful designs that enhance user experience and drive engagement.',
        ],
        description:
          'Create intuitive and visually appealing user interfaces and experiences.',
        jobDescriptionInfo:
          'Design engaging UI/UX for various web and mobile applications.',
        requirements: [
          '1+ years of experience in UI/UX design',
          'Proficiency in design tools like Figma or Adobe XD',
          'Strong understanding of user-centered design principles',
        ],
        preferredSkills: [
          'Experience with user testing and research',
          'Knowledge of HTML, CSS, and JavaScript',
          'Ability to work collaboratively in a team',
        ],
        productDesigner:
          'Collaborate with product managers and developers to create high-quality designs.',
        expirationDate: '2024-11-05',
        phone: '+1-234-567-8900',
        email: 'careers@designwaves.com',
        salary: '65,000/year',
        companyLogo: 'assets/images/jobs/job-3.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 12,
        title: 'Junior Full-Stack Developert',
        company: 'CloudMinds Technologies',
        location: 'Canada',
        type: 'Full time',
        posted: '19 mins ago',
        about: [
          'CloudMinds Technologies is a Canadian company specializing in full-stack development for modern web applications.',
          'We provide innovative solutions by integrating cutting-edge technologies and frameworks.',
          'Our team emphasizes professional growth, collaboration, and delivering high-quality applications to clients.',
          'At CloudMinds, we are committed to empowering businesses with robust and scalable web solutions.',
        ],
        description:
          'Work on both front-end and back-end technologies to develop web apps.',
        jobDescriptionInfo:
          'Assist in the development of full-stack web applications.',
        requirements: [
          '1+ years of experience in full-stack development',
          'Proficiency in JavaScript, HTML, and CSS',
          'Familiarity with Node.js and frontend frameworks',
        ],
        preferredSkills: [
          'Experience with databases (SQL or NoSQL)',
          'Knowledge of version control (Git)',
          'Ability to work in an Agile environment',
        ],
        productDesigner:
          'Collaborate with the design and development teams to ensure a seamless user experience.',
        expirationDate: '2024-11-10',
        phone: '+1-123-456-7890',
        email: 'jobs@cloudminds.com',
        salary: '55,000/Month',
        companyLogo: 'assets/images/jobs/job-4.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 13,
        title: 'Junior Front-End Developer',
        company: 'PixelTech',
        location: 'Berlin, Germany',
        type: 'Full time',
        posted: '3 mins ago',
        about: [
          'PixelTech is a Berlin-based software development company focused on delivering cutting-edge front-end solutions.',
          'We specialize in creating fast, scalable, and responsive applications using the latest technologies.',
          'Our team values creativity, technical expertise, and collaborative problem-solving to achieve client goals.',
          'At PixelTech, we aim to transform ideas into digital experiences that inspire and engage users.',
        ],
        description:
          'Implement web designs using modern frameworks like React or Angular.',
        jobDescriptionInfo:
          'Develop user-facing features and optimize applications for speed and scalability.',
        requirements: [
          '1+ years of experience in frontend development',
          'Proficiency in HTML, CSS, and JavaScript',
          'Familiarity with React or Angular',
        ],
        preferredSkills: [
          'Knowledge of responsive design techniques',
          'Experience with RESTful APIs',
          'Ability to troubleshoot and debug',
        ],
        productDesigner:
          'Work closely with designers to implement visually appealing and functional web pages.',
        expirationDate: '2024-11-15',
        phone: '+49-123-456-7890',
        email: 'careers@pixeltech.com',
        salary: '€45,000/Month',
        companyLogo: 'assets/images/jobs/job-5.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 14,
        title: 'Junior Back-End Engineer',
        company: 'Skyline Software',
        location: 'Austin, USA',
        type: 'Full time',
        posted: '3 hour ago',
        about: [
          'Skyline Software, headquartered in Austin, is renowned for its expertise in backend development and scalable architectures.',
          'We focus on building efficient and secure server-side systems that integrate seamlessly with frontend applications.',
          'Our team prioritizes innovation, precision, and adaptability to meet the dynamic needs of our clients.',
          'At Skyline Software, we are dedicated to delivering backend solutions that empower businesses to thrive.',
        ],
        description:
          'Design, develop, and maintain server-side logic with Python or Java.',
        jobDescriptionInfo:
          'Develop backend services and APIs to support frontend applications.',
        requirements: [
          '1+ years of experience in backend development',
          'Proficiency in Python or Java',
          'Familiarity with database technologies (SQL, MongoDB)',
        ],
        preferredSkills: [
          'Experience with microservices architecture',
          'Understanding of RESTful API design',
          'Knowledge of containerization (Docker) is a plus',
        ],
        productDesigner:
          'Collaborate with frontend developers to integrate user-facing elements with server-side logic.',
        expirationDate: '2024-11-20',
        phone: '+1-512-345-6789',
        email: 'jobs@skyline.com',
        salary: '$60,000/year',
        companyLogo: 'assets/images/jobs/job-6.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 15,
        title: 'UI/UX Designer',
        company: ' BrightPixel Studios',
        location: 'Cairo',
        type: 'Full time',
        posted: '3 mins ago',
        about: [
          'BrightPixel Studios is a Cairo-based creative agency specializing in UI/UX design for web and mobile platforms.',
          'We are committed to crafting user-friendly and aesthetically pleasing designs that enhance user experiences.',
          'Our team blends innovation, attention to detail, and user-centric principles to deliver outstanding projects.',
          'At BrightPixel Studios, we pride ourselves on helping businesses achieve their goals through compelling design solutions.',
        ],
        description:
          'Design user-friendly interfaces and conduct usability testing.',
        jobDescriptionInfo:
          'Create wireframes, prototypes, and high-fidelity designs for various projects.',
        requirements: [
          '2+ years of experience in UI/UX design',
          'Proficiency in design tools like Sketch or Figma',
          'Strong portfolio showcasing design projects',
        ],
        preferredSkills: [
          'Experience with user research and testing',
          'Understanding of HTML and CSS',
          'Ability to work under tight deadlines',
        ],
        productDesigner:
          'Work closely with developers to implement and maintain designs across platforms.',
        expirationDate: '2024-12-01',
        phone: '+20-123-456-7890',
        email: 'careers@brightpixel.com',
        salary: '35,000/year',
        companyLogo: 'assets/images/jobs/job-7.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 16,
        title: 'Junior Front-End Developer',
        company: 'InnovateTech',
        location: 'San Francisco, USA',
        type: 'Full time',
        posted: '3 mins ago',
        about: [
          'InnovateTech is a San Francisco-based company committed to advancing web development through cutting-edge technologies.',
          'We specialize in creating responsive and interactive web applications with a strong emphasis on user experience.',
          'Our team thrives on collaboration and creativity, driving us to continuously innovate and push the boundaries of frontend development.',
          'At InnovateTech, we value passion, skill, and an eagerness to learn as key ingredients for success in our dynamic environment.',
        ],
        description:
          'Build user-friendly and responsive interfaces using JavaScript and CSS.',
        jobDescriptionInfo:
          'Assist in creating interactive web applications that enhance user engagement.',
        requirements: [
          '1+ years of experience in frontend development',
          'Strong skills in HTML, CSS, and JavaScript',
          'Familiarity with frontend frameworks',
        ],
        preferredSkills: [
          'Experience with version control (Git)',
          'Knowledge of accessibility standards',
          'Strong problem-solving skills',
        ],
        productDesigner:
          'Collaborate with UX designers to ensure an optimal user experience across applications.',
        expirationDate: '2024-12-05',
        phone: '+1-415-678-9012',
        email: 'jobs@innovate.tech',
        salary: '$58,000/year',
        companyLogo: 'assets/images/jobs/job-8.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 17,
        title: 'Back-End Developer',
        company: 'DataBridge Systems',
        location: 'Cairo',
        type: 'Full time',
        posted: '2 days ago',
        about: [
          'DataBridge Systems is a Cairo-based tech company specializing in creating robust and scalable backend services.',
          'We focus on building high-performance APIs and backend architectures that ensure reliability and speed.',
          'Our team thrives on collaboration and innovative thinking, leveraging the latest technologies to build scalable systems.',
          'At DataBridge Systems, we aim to empower businesses by providing reliable and efficient backend solutions that scale as they grow.',
        ],
        description:
          'Develop server-side logic, manage databases, and optimize APIs.',
        jobDescriptionInfo:
          'Design and implement backend services and database systems.',
        requirements: [
          '2+ years of experience in backend development',
          'Proficiency in Node.js, Python, or Java',
          'Experience with relational and non-relational databases',
        ],
        preferredSkills: [
          'Knowledge of cloud services (AWS, Azure)',
          'Familiarity with containerization and orchestration',
          'Strong analytical and troubleshooting skills',
        ],
        productDesigner:
          'Work with front-end teams to integrate and optimize API interactions.',
        expirationDate: '2024-12-10',
        phone: '+20-234-567-8901',
        email: 'careers@databridge.com',
        salary: '33.000/Month',
        companyLogo: 'assets/images/jobs/job-9.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 18,
        title: 'Junior UI Designer',
        company: 'CreativeCode Studios',
        location: 'Remote',
        type: 'Full time',
        posted: '3 days ago',
        about: [
          'CreativeCode Studios is a remote-based creative agency focused on providing innovative UI/UX design solutions for web and mobile applications.',
          'We believe in creating designs that are both visually appealing and user-friendly, ensuring an exceptional user experience.',
          'Our team collaborates closely with developers and product managers to turn ideas into beautiful digital experiences.',
          'At CreativeCode Studios, we are passionate about design and creating intuitive user interfaces that help businesses engage with their customers effectively.',
        ],
        description:
          'Design engaging user interfaces and collaborate with UX teams.',
        jobDescriptionInfo:
          'Assist in the creation of designs for web and mobile applications.',
        requirements: [
          '1+ years of experience in UI design',
          'Proficiency in design software like Figma or Adobe XD',
          'Understanding of color theory and typography',
        ],
        preferredSkills: [
          'Experience with HTML/CSS',
          'Familiarity with design systems',
          'Ability to present design ideas clearly',
        ],
        productDesigner:
          'Collaborate with UX researchers to enhance user experience through design.',
        expirationDate: '2024-12-15',
        phone: '+1-345-678-9012',
        email: 'jobs@creativecode.com',
        salary: '€30,000/Month',
        companyLogo: 'assets/images/jobs/job-10.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 19,
        title: 'Junior Front-End Developer (React)',
        company: 'PixelHub',
        location: 'New York, USA',
        type: 'Part time',
        posted: '12 mins ago',
        about: [
          'PixelHub is a New York-based company specializing in creating modern, dynamic web applications that use the latest web technologies.',
          'We focus on building highly responsive websites using React and other cutting-edge frontend frameworks.',
          'Our team works closely with designers to ensure the delivery of visually stunning and functionally effective web applications.',
          'At PixelHub, we are passionate about creating seamless user experiences that enhance the digital presence of our clients.',
        ],
        description:
          'Build responsive and dynamic web pages using React and CSS.',
        jobDescriptionInfo:
          'Contribute to the development of user-friendly web applications.',
        requirements: [
          '1+ years of experience with React',
          'Strong skills in HTML, CSS, and JavaScript',
          'Familiarity with RESTful APIs',
        ],
        preferredSkills: [
          'Knowledge of state management libraries (Redux)',
          'Ability to work in a team environment',
          'Strong attention to detail',
        ],
        productDesigner:
          'Work alongside designers to implement visually appealing and functional web pages.',
        expirationDate: '2024-12-20',
        phone: '+1-456-789-0123',
        email: 'careers@pixelhub.com',
        salary: '$60,000/Month',
        companyLogo: 'assets/images/jobs/job-11.png',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 20,
        title: 'Junior Back-End Developer',
        company: 'CodeForge',
        location: 'London, UK',
        type: 'Remote',
        posted: '3 mins ago',
        about: [
          'CodeForge is a London-based software development company specializing in creating high-quality backend systems.',
          'We focus on building fast, secure, and scalable APIs that power the next generation of web applications.',
          'Our team is dedicated to crafting backend solutions that are both efficient and adaptable to changing business needs.',
          'At CodeForge, we value innovation and collaboration to create exceptional backend architectures that meet our clients’ demands.',
        ],
        description:
          'Develop and maintain server-side applications using Node.js and Mong',
        jobDescriptionInfo:
          'Build scalable and efficient backend services and databases.',
        requirements: [
          '1+ years of experience in backend development',
          'Proficiency in Node.js and MongoDB',
          'Understanding of API development',
        ],
        preferredSkills: [
          'Experience with Agile methodologies',
          'Knowledge of authentication and security best practices',
          'Strong problem-solving skills',
        ],
        productDesigner:
          'Collaborate with front-end developers to ensure seamless integration of services.',
        expirationDate: '2024-12-25',
        phone: '+44-123-456-7890',
        email: 'jobs@codeforge.com',
        salary: '£40,000/Month',
        companyLogo: 'assets/images/jobs/job-12.png',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 21,
        title: 'Junior Flutter Developer',
        company: ' AppX Innovations',
        location: 'Canada',
        type: 'Full time',
        posted: '3 days ago',
        about: [
          'AppX Innovations is a Canada-based company specializing in mobile app development using Flutter.',
          'We are dedicated to creating high-performance, cross-platform mobile applications that run seamlessly on both Android and iOS devices.',
          'Our team values collaboration, innovation, and efficiency, and we work to deliver exceptional mobile experiences for users.',
          'At AppX Innovations, we are committed to empowering businesses by providing the best mobile solutions to reach their customers.',
        ],
        description: 'Build cross-platform mobile apps with Flutter and Dart.',
        jobDescriptionInfo:
          'Work on the development of mobile applications targeting both Android and iOS platforms.',
        requirements: [
          'Familiarity with Flutter and Dart',
          'Basic understanding of mobile app development principles',
          'Experience with RESTful APIs is a plus',
        ],
        preferredSkills: [
          'Knowledge of mobile UI/UX principles',
          'Ability to work collaboratively in a team',
          'Experience with version control (Git)',
        ],
        productDesigner:
          'Collaborate with designers and other developers to create seamless applications.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8901',
        email: 'jobs@appxinnovations.com',
        salary: 'CAD 55,000/Month',
        companyLogo: 'assets/images/jobs/job-13.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 22,
        title: 'Full-Stack Developer (Flutter/Node.js)',
        company: 'CloudStack',
        location: 'San Francisco, USA',
        type: 'Part time',
        posted: '3 mins ago',
        about: [
          'CloudStack is a San Francisco-based technology company specializing in cloud-based mobile and backend solutions.',
          'We are focused on building innovative full-stack applications that bridge the gap between mobile and server-side technologies.',
          'Our team thrives in a fast-paced, collaborative environment, where we deliver high-quality solutions to meet client needs.',
          'At CloudStack, we empower businesses to scale through modern technologies, focusing on delivering impactful results.',
        ],
        description:
          'Work on Flutter mobile apps and build server-side APIs using Node.js.',
        jobDescriptionInfo:
          'Develop full-stack applications with a focus on mobile and backend integration.',
        requirements: [
          'Proficiency in Flutter and Node.js',
          'Experience with databases like MongoDB or MySQL',
          'Basic understanding of RESTful API development',
        ],
        preferredSkills: [
          'Familiarity with Agile methodologies',
          'Knowledge of CI/CD pipelines',
          'Strong problem-solving skills',
        ],
        productDesigner:
          'Collaborate with cross-functional teams to define, design, and ship new features.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8902',
        email: 'careers@cloudstack.com',
        salary: ' $70,000/Month',
        companyLogo: 'assets/images/jobs/job-43.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 23,
        title: 'Junior Flutter Developer',
        company: 'TechNest',
        location: ' Germany',
        type: 'Full time',
        posted: '10 mins ago',
        about: [
          'CodeForge is a London-based software development company specializing in creating high-quality backend systems.',
          'We focus on building fast, secure, and scalable APIs that power the next generation of web applications.',
          'Our team is dedicated to crafting backend solutions that are both efficient and adaptable to changing business needs.',
          'At CodeForge, we value innovation and collaboration to create exceptional backend architectures that meet our clients’ demands.',
        ],
        description:
          'Develop user-friendly mobile apps for Android and iOS using Flutter.',
        jobDescriptionInfo:
          'Create high-quality mobile applications focusing on user experience and performance.',
        requirements: [
          'Familiarity with Flutter framework and Dart programming',
          'Understanding of mobile development principles',
          'Experience with REST APIs is a plus',
        ],
        preferredSkills: [
          'Knowledge of design patterns and mobile architecture',
          'Ability to work in a team and communicate effectively',
          'Familiarity with Git version control',
        ],
        productDesigner:
          'Collaborate closely with UI/UX designers to ensure app usability and performance.',
        expirationDate: '2024-12-31',
        phone: '+49-234-567-8903',
        email: 'jobs@technest.com',
        salary: '€45,000/Month',
        companyLogo: 'assets/images/jobs/job-15 .png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 24,
        title: 'Junior Back-End Developer (Python)',
        company: 'DataWave',
        location: ' India',
        type: 'Full time',
        posted: '2 mins ago',
        about: [
          'DataWave is an India-based software company that specializes in creating scalable backend systems using Python and Django.',
          'We focus on building high-performance backend architectures and services to power modern applications.',
          'Our team is dedicated to providing reliable and efficient backend solutions that are adaptable to the ever-evolving needs of businesses.',
          'At DataWave, we are driven by a passion for technology and a commitment to delivering excellence in every project we undertake.',
        ],
        description:
          'Build and optimize back-end services and APIs using Python and Django',
        jobDescriptionInfo:
          'Design and implement scalable back-end systems and services.',
        requirements: [
          'Proficiency in Python and Django',
          'Basic understanding of RESTful API development',
          'Experience with database management systems',
        ],
        preferredSkills: [
          'Knowledge of front-end technologies is a plus',
          'Experience with version control (Git)',
          'Strong problem-solving skills',
        ],
        productDesigner:
          'Work with front-end developers to ensure seamless integration of services.',
        expirationDate: '2024-12-31',
        phone: '+91-234-567-8904',
        email: 'careers@datawave.com',
        salary: '₹500,000/year',
        companyLogo: 'assets/images/jobs/job-16.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 25,
        title: 'Junior Front-End Developer (Angular)',
        company: 'WebMinds',
        location: 'Cairo',
        type: 'Remote',
        posted: '5 days ago',
        about: [
          'WebMinds is a Cairo-based software development company that specializes in building modern web applications using Angular.',
          'We focus on delivering high-quality, scalable solutions with a focus on user experience and performance.',
          'Our team works closely with clients to understand their needs and deliver web applications that exceed expectations.',
          'At WebMinds, we are passionate about creating impactful web solutions and fostering a collaborative, innovative work environment.',
        ],
        description:
          'Build responsive front-end components using Angular and TypeScript.',
        jobDescriptionInfo:
          'Develop user-facing applications that provide a great user experience.',
        requirements: [
          'Familiarity with Angular and TypeScript',
          'Strong skills in HTML, CSS, and JavaScript',
          'Basic understanding of REST APIs',
        ],
        preferredSkills: [
          'Knowledge of UI/UX design principles',
          'Experience with Git version control',
          'Ability to work in a team',
        ],
        productDesigner:
          'Collaborate with designers to translate UI/UX requirements into functional applications.',
        expirationDate: '2024-12-31',
        phone: '+20-234-567-8905',
        email: 'jobs@webminds.com',
        salary: '60,000/Month',
        companyLogo: 'assets/images/jobs/job-17.png',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 26,
        title: 'Junior Flutter Developer',
        company: 'MobileX',
        location: 'Cairo',
        type: 'Remote',
        posted: 'Week ago',
        about: [
          'MobileX is a Cairo-based company that focuses on creating cutting-edge mobile applications using Flutter.',
          'We are dedicated to delivering high-quality, user-friendly mobile applications that meet the needs of our clients.',
          'Our team works closely with designers and developers to create seamless and visually appealing mobile experiences.',
          'At MobileX, we prioritize collaboration and innovation, ensuring that every app we create offers a superior user experience.',
        ],
        description:
          'Create mobile applications with Flutter, focusing on user interface and experience.',
        jobDescriptionInfo:
          'Develop visually appealing and functional mobile applications.',
        requirements: [
          'Familiarity with Flutter and Dart',
          'Basic understanding of mobile development principles',
          'Experience with REST APIs is a plus',
        ],
        preferredSkills: [
          'Knowledge of mobile UI/UX principles',
          'Ability to work collaboratively in a team',
          'Experience with version control (Git)',
        ],
        productDesigner:
          'Collaborate with designers to enhance user experience and application usability.',
        expirationDate: '2024-12-31',
        phone: '+20-345-678-9010',
        email: 'jobs@mobilex.com',
        salary: '45,000/Month',
        companyLogo: 'assets/images/jobs/job-18.png',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 27,
        title: 'Junior Software Engineer (Full-Stack)',
        company: 'NextGen Innovations',
        location: 'New York, NY',
        type: 'Full time',
        posted: '5 sec ago',
        about: [
          'NextGen Innovations is a New York-based technology company focused on developing innovative software solutions.',
          'We specialize in delivering full-stack web applications with a strong emphasis on performance and scalability.',
          'Our team thrives in a fast-paced, collaborative environment, where we aim to build the next generation of web technologies.',
          'At NextGen Innovations, we are committed to empowering businesses with cutting-edge software solutions to stay ahead in the digital world.',
        ],
        description:
          'Work on both front-end and back-end tasks using React and Node.js.',
        jobDescriptionInfo:
          'Develop full-stack applications with a focus on performance and scalability.',
        requirements: [
          'Familiarity with React and Node.js',
          'Basic understanding of databases (SQL or NoSQL)',
          'Experience with RESTful APIs',
        ],
        preferredSkills: [
          'Knowledge of CI/CD processes',
          'Strong problem-solving skills',
          'Ability to work in a team environment',
        ],
        productDesigner:
          'Collaborate with cross-functional teams to deliver high-quality software solutions.',
        expirationDate: '2024-12-31',
        phone: '+1-456-789-0124',
        email: 'jobs@nextgeninnovations.com',
        salary: '$50,000/Month',

        companyLogo: 'assets/images/jobs/job-19.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 28,
        title: 'Junior Front-End Developer (Vue.js)',
        company: 'CodeSphere',
        location: 'Canda',
        type: 'Part time',
        posted: '3 days ago',
        about: [
          'CodeSphere is a Canada-based company specializing in building high-quality front-end applications using Vue.js.',
          'We create modern, responsive, and dynamic user interfaces that engage users and enhance their experience.',
          'Our team is passionate about working with the latest technologies to deliver innovative solutions to clients.',
          'At CodeSphere, we foster a collaborative work environment where creativity and problem-solving are key to our success.',
        ],
        description:
          'Develop dynamic and responsive front-end features using Vue.js.',
        jobDescriptionInfo:
          'Create engaging user interfaces and ensure a smooth user experience.',
        requirements: [
          'Familiarity with Vue.js and JavaScript',
          'Strong skills in HTML and CSS',
          'Basic understanding of REST APIs',
        ],
        preferredSkills: [
          'Experience with Git version control',
          'Knowledge of UI/UX principles',
          'Ability to work in a team',
        ],
        productDesigner:
          'Collaborate with designers to implement innovative user experiences.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8906',
        email: 'jobs@codesphere.com',
        salary: '€35,000/year',
        companyLogo: 'assets/images/jobs/job-20.png',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 29,
        title: 'Junior Front-End Developer (React)',
        company: 'WebForge',
        location: 'Freelance',
        type: 'Full time',
        posted: '2 Week ago',
        about: [
          'WebForge is a freelance-focused company that specializes in delivering interactive and visually appealing web applications using React.',
          'Our goal is to create seamless user experiences with dynamic and responsive interfaces.',
          'We collaborate with clients to design and build innovative web solutions that enhance business outcomes.',
          'At WebForge, we value creativity, technical expertise, and the ability to adapt to changing client needs.',
        ],
        description:
          ' Develop interactive and visually appealing web pages with React.',
        jobDescriptionInfo:
          'Create dynamic user interfaces that enhance user engagement.',
        requirements: [
          'Familiarity with React and JavaScript',
          'Strong skills in HTML and CSS',
          'Basic understanding of REST APIs',
        ],
        preferredSkills: [
          'Experience with UI/UX design',
          'Knowledge of Git version control',
          'Ability to work independently and in a team',
        ],
        productDesigner:
          'Collaborate with cross-functional teams to deliver high-quality web applications.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8907',
        email: 'jobs@webforge.com',
        salary: '$35,000/Month',
        companyLogo: 'assets/images/jobs/job-21.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 30,
        title: 'Junior Software Engineer (JavaScript)',
        company: 'TechNova',
        location: 'Remote',
        type: 'Full time',
        posted: '19 mins ago',
        about: [
          'TechNova is a remote-first software company that focuses on delivering modern web applications using JavaScript.',
          'We emphasize building scalable, high-performance applications that are easy to maintain and adapt to the evolving needs of our clients.',
          'Our team embraces Agile methodologies, fostering collaboration and continuous improvement.',
          'At TechNova, we strive to stay ahead of the curve by leveraging the latest technologies to build powerful software solutions.',
        ],
        description:
          'Develop full-stack web applications using JavaScript frameworks.',
        jobDescriptionInfo:
          'Build scalable applications with a focus on performance and maintainability.',
        requirements: [
          'Familiarity with JavaScript frameworks (React, Angular, Vue)',
          'Basic understanding of back-end technologies',
          'Experience with RESTful APIs',
        ],
        preferredSkills: [
          'Knowledge of Agile methodologies',
          'Strong problem-solving skills',
          'Ability to work collaboratively',
        ],
        productDesigner:
          'Collaborate with teams to develop innovative software solutions.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8908',
        email: 'jobs@technova.com',
        salary: 'MYR 60,000/Month',
        companyLogo: 'assets/images/jobs/job-22.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 31,
        title: 'Junior Flutter Developer',
        company: 'GFlutterWorks',
        location: 'Remote',
        type: 'Full time',
        posted: '31 sec ago',
        about: [
          'GFlutterWorks is a remote-first company specializing in building responsive mobile apps using Flutter and Dart.',
          'We focus on developing high-performance applications that deliver great user experiences.',
          'Our team collaborates with designers to create mobile solutions that meet user expectations and business goals.',
          'At GFlutterWorks, we prioritize innovation and growth, ensuring our apps are at the forefront of mobile technology.',
        ],
        description:
          'Create engaging and responsive mobile apps using Flutter and Dart.',
        jobDescriptionInfo:
          'Develop and maintain mobile applications focusing on performance and user experience.',
        requirements: [
          'Familiarity with Flutter and Dart',
          'Basic understanding of mobile app development principles',
          'Experience with RESTful APIs is a plus',
        ],
        preferredSkills: [
          'Knowledge of mobile UI/UX principles',
          'Ability to work collaboratively in a team',
          'Experience with Git version control',
        ],
        productDesigner:
          'Work closely with UI/UX designers to create intuitive applications.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8909',
        email: 'jobs@gflutterworks.com',
        salary: '$47,000/Month',
        companyLogo: 'assets/images/jobs/job-23.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 32,
        title: 'Junior Flutter Developer',
        company: 'DevLink Technologies',
        location: 'Remote',
        type: 'Full time',
        posted: '38 mins ago',
        about: [
          'DevLink Technologies is a remote company that specializes in building high-performance mobile applications using Flutter.',
          'We are committed to delivering fast, scalable mobile solutions that provide a seamless user experience.',
          'Our team works closely with designers to ensure our apps meet both functional and aesthetic goals.',
          'At DevLink Technologies, we value innovation and collaboration, always aiming to deliver cutting-edge mobile experiences.',
        ],
        description:
          'Build responsive and fast mobile applications using Flutter and Dart.',
        jobDescriptionInfo:
          'Create high-performance mobile applications for both iOS and Android platforms.',
        requirements: [
          'Familiarity with Flutter framework and Dart programming',
          'Understanding of mobile app development principles',
          'Experience with RESTful APIs',
        ],
        preferredSkills: [
          'Knowledge of mobile UI/UX design',
          'Ability to work in an Agile environment',
          'Experience with version control (Git)',
        ],
        productDesigner:
          'Collaborate with designers to deliver engaging user experiences.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8910',
        email: 'careers@devlinktech.com',
        salary: '$50,000/Month',
        companyLogo: 'assets/images/jobs/job-24.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 33,
        title: 'Junior Flutter Developer',
        company: 'AppTide Solutions',
        location: 'Freelance',
        type: 'Part time',
        posted: '3 mins ago',
        about: [
          'AppTide Solutions is a freelance-oriented company that specializes in developing mobile apps using Flutter.',
          'We focus on delivering high-quality mobile solutions that are both user-friendly and efficient.',
          'Our team works remotely and embraces flexibility, allowing us to deliver projects that meet the specific needs of our clients.',
          'At AppTide Solutions, we prioritize innovation and seamless user experiences in every mobile app we create.',
        ],
        description:
          'Develop cross-platform mobile apps using Flutter and Dart.',
        salary: '$ 22,000/Month',
        companyLogo: 'assets/images/jobs/job-25.png',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 34,
        title: 'Software Engineer Intern',
        company: ' InnoWave',
        location: 'Germany',
        type: 'Part time',
        posted: '10 hour ago',
        about: [
          'InnoWave is a German-based technology company that offers innovative mobile app development services.',
          'We focus on creating tailored applications that meet the specific needs of our clients.',
          'Our team collaborates closely with clients to bring their ideas to life and deliver high-quality mobile apps.',
          'At InnoWave, we value creativity, attention to detail, and a strong understanding of mobile UI/UX principles.',
        ],
        description:
          'Assist in developing software modules and testing web applications.',
        jobDescriptionInfo:
          'Create engaging mobile applications for various clients and projects.',
        requirements: [
          'Familiarity with Flutter and Dart',
          'Basic understanding of mobile app development',
          'Experience with RESTful APIs',
        ],
        preferredSkills: [
          'Knowledge of mobile UI/UX principles',
          'Ability to manage time effectively',
          'Experience with version control (Git)',
        ],
        productDesigner:
          'Work with clients to create applications that meet their needs.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8911',
        email: 'jobs@apptidesolutions.com',
        salary: ' €30,000/Month',
        companyLogo: 'assets/images/jobs/job-26.png',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 35,
        title: 'Junior DevOps Engineer',
        company: 'CloudNet Technologies',
        location: 'Remote',
        type: 'Full time',
        posted: '8 hour ago',
        about: [
          'CloudNet Technologies is a remote-first company that specializes in DevOps automation and software deployment.',
          'We work with cutting-edge tools and cloud platforms to automate infrastructure and streamline deployment processes.',
          'Our team is dedicated to delivering high-performance solutions that meet the needs of modern software development.',
          'At CloudNet Technologies, we are committed to continuous learning and collaboration in a fast-paced tech environment.',
        ],
        description:
          'Automate and manage infrastructure for software deployment.',
        jobDescriptionInfo:
          'Gain hands-on experience in software development and testing.',
        requirements: [
          'Basic knowledge of programming languages (Java, C#, Python)',
          'Understanding of web technologies (HTML, CSS, JavaScript)',
          'Willingness to learn and adapt',
        ],
        preferredSkills: [
          'Experience with Git version control',
          'Strong analytical skills',
          'Good communication skills',
        ],
        productDesigner: 'Collaborate with senior developers on projects.',
        expirationDate: '2024-12-31',
        phone: '+49-234-567-8912',
        email: 'careers@innowave.com',
        salary: '$50,000/Month',
        companyLogo: 'assets/images/jobs/job-27.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 36,
        title: 'Front-End Developer',
        company: ' UIX Solutions',
        location: 'Cairo',
        type: 'Part time',
        posted: '15 sec ago',
        about: [
          'UIX Solutions is a Cairo-based company focused on creating intuitive and responsive user interfaces.',
          'We integrate the latest front-end technologies to deliver optimal user experiences.',
          'Our team works collaboratively with cross-functional teams to ensure seamless deployment and cloud management.',
          'At UIX Solutions, we strive to be at the forefront of innovation and maintain a focus on delivering quality solutions.',
        ],
        description:
          'Design and implement user interfaces using HTML, CSS, and JavaScript.',
        jobDescriptionInfo:
          'Support development teams with CI/CD practices and cloud infrastructure management.',
        requirements: [
          'Familiarity with DevOps tools (Docker, Jenkins)',
          'Basic understanding of cloud platforms (AWS, Azure)',
          'Experience with scripting languages (Bash, Python)',
        ],
        preferredSkills: [
          'Knowledge of version control (Git)',
          'Strong problem-solving skills',
          'Ability to work in a team',
        ],
        productDesigner:
          'Collaborate with developers to improve deployment processes.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8913',
        email: 'jobs@cloudnettech.com',
        salary: '32.000/Month',
        companyLogo: 'assets/images/jobs/job-28.png',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 37,
        title: 'Mobile App Developer (Flutter)',
        company: 'CodeBlitz',
        location: 'New York, NY',
        type: 'Full time',
        posted: '8 mins ago',
        about: [
          'CodeBlitz is a New York-based company specializing in developing high-quality mobile apps using Flutter.',
          'We focus on delivering cross-platform mobile applications that are visually appealing and scalable.',
          'Our team works closely with designers and developers to create exceptional user experiences for mobile apps.',
          'At CodeBlitz, we aim to push the boundaries of mobile app development by using innovative tools and technologies.',
        ],
        description:
          'Build scalable mobile applications using Flutter for Android and iOS.',
        jobDescriptionInfo:
          'Create visually appealing and user-friendly web applications.',
        requirements: [
          'Proficiency in HTML, CSS, and JavaScript',
          'Basic understanding of front-end frameworks (React, Vue)',
          'Experience with RESTful APIs',
        ],
        preferredSkills: [
          'Knowledge of responsive design principles',
          'Strong attention to detail',
          'Ability to work independently',
        ],
        productDesigner:
          'Work with designers to implement effective user interfaces.',
        expirationDate: '2024-12-31',
        phone: '+20-234-567-8914',
        email: 'jobs@uixsolutions.com',
        salary: '$65,000/Month',
        companyLogo: 'assets/images/jobs/job-29.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 38,
        title: 'Junior Software Engineer',
        company: 'CodeBridge Solutions',
        location: 'Remote',
        type: 'Full time',
        posted: '5 hour ago',
        about: [
          'CodeBridge Solutions is a leading software development company focused on creating innovative tech solutions for clients worldwide.',
          'We specialize in custom software development, bringing ideas to life with cutting-edge technologies.',
          'Our team thrives in a fast-paced, collaborative environment where we value creativity and excellence.',
          'At CodeBridge Solutions, we are committed to delivering reliable, scalable software solutions that drive business success.',
        ],
        description:
          'Develop and maintain software applications, focusing on bug fixes and feature updates.',
        jobDescriptionInfo:
          'Develop and maintain high-quality mobile applications targeting multiple platforms.',
        requirements: [
          'Proficiency in Flutter and Dart',
          'Experience with RESTful APIs',
          'Basic understanding of mobile development best practices',
        ],
        preferredSkills: [
          'Knowledge of Firebase integration',
          'Strong problem-solving skills',
          'Ability to work collaboratively',
        ],
        productDesigner: 'Collaborate with designers to enhance app usability.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8915',
        email: 'jobs@codeblitz.com',
        salary: '$60,000/Month',
        companyLogo: 'assets/images/jobs/job-30.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 39,
        title: 'Junior Software Engineer (Remote)',
        company: 'NextGen Technologies',
        location: 'Remote',
        type: 'part time',
        posted: '3 mins ago',
        about: [
          'NextGen Technologies is at the forefront of technological advancement, specializing in AI-driven solutions and cutting-edge software products.',
          'We believe in pushing the boundaries of innovation and technology to solve complex challenges.',
          'Our team is passionate about developing high-performance, scalable solutions for clients around the world.',
          'At NextGen Technologies, we foster a collaborative culture where learning and growth are encouraged.',
        ],
        description:
          'Assist in building and maintaining software products, collaborating with cross-functional teams.',
        jobDescriptionInfo:
          'Support the development team with various software projects.',
        requirements: [
          'Familiarity with programming languages (Java, Python, JavaScript)',
          'Basic understanding of software development life cycle',
          'Willingness to learn and adapt',
        ],
        preferredSkills: [
          'Experience with Git version control',
          'Strong analytical skills',
          'Good communication skills',
        ],
        productDesigner:
          'Collaborate with team members to deliver high-quality software.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8916',
        email: 'jobs@codebridge.com',
        salary: '$55,000/Month',
        companyLogo: 'assets/images/jobs/job-31.png',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 40,
        title: 'Junior Flutter Developer (Remote)',
        company: ' AppGlobe',
        location: 'Remote',
        type: 'Full time',
        posted: '3 hour ago',
        about: [
          'AppGlobe is a rapidly growing mobile development firm focused on delivering robust and scalable apps across platforms.',
          'We prioritize user experience and strive to create intuitive, efficient, and visually appealing mobile solutions.',
          'Our development team works closely with designers to create apps that delight users.',
          'At AppGlobe, we value collaboration, innovation, and the pursuit of excellence in all our projects.',
        ],
        description:
          'Create feature-rich mobile applications using Flutter, ensuring cross-platform compatibility.',
        jobDescriptionInfo:
          'Develop mobile apps that provide an exceptional user experience.',
        requirements: [
          'Proficiency in Flutter and Dart',
          'Understanding of mobile app development lifecycle',
          'Experience with RESTful APIs',
        ],
        preferredSkills: [
          'Knowledge of state management solutions',
          'Strong analytical and problem-solving skills',
          'Ability to work collaboratively',
        ],
        productDesigner: 'Collaborate with designers to enhance app usability.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8918',
        email: 'jobs@appglobe.com',
        salary: '$50,000/Month',
        companyLogo: 'assets/images/jobs/job-32.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 41,
        title: 'Backend Developer (Junior)',
        company: ' DataFlow Solutions',
        location: 'Canada',
        type: 'Full time',
        posted: '2 mins ago',
        about: [
          'DataFlow Solutions is a dynamic software development company specializing in back-end development and data processing solutions.',
          'We are committed to delivering high-quality, scalable software solutions for a wide range of industries.',
          'Our team values collaboration, continuous learning, and the use of modern technologies to solve real-world challenges.',
          'At DataFlow Solutions, we foster a culture of innovation, ensuring that we stay ahead of the curve with cutting-edge development practices.',
        ],
        description:
          'Develop server-side logic and manage database integrations for web applications.',
        jobDescriptionInfo:
          'Support backend development with database design and server logic.',
        requirements: [
          'Familiarity with back-end languages (Node.js, Python)',
          'Basic understanding of database systems (SQL, NoSQL)',
          'Experience with RESTful APIs',
        ],
        preferredSkills: [
          'Knowledge of cloud services (AWS, Azure)',
          'Strong problem-solving skills',
          'Ability to work in a team',
        ],
        productDesigner:
          'Work closely with front-end developers to deliver full-stack solutions.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8919',
        email: 'jobs@dataflowsolutions.com',
        salary: 'CAD 58,000/Month',
        companyLogo: 'assets/images/jobs/job-33.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 42,
        title: 'Entry-Level Mobile App Developer',
        company: 'AppInspire',
        location: 'India',
        type: 'Full time',
        posted: '6 mins ago',
        about: [
          'AppInspire is a leading mobile application development company, focused on creating innovative apps that engage and delight users.',
          'We emphasize delivering high-performance applications that offer a seamless user experience across different devices.',
          'Our team works together to ensure that each mobile app is not only functional but also user-friendly and intuitive.',
          'At AppInspire, we value creativity, teamwork, and continuous growth in the tech industry.',
        ],
        description:
          'Build mobile apps for Android using Java or Kotlin, and collaborate with senior developers.',
        jobDescriptionInfo:
          'Develop high-quality mobile applications that enhance user engagement.',
        requirements: [
          'Basic knowledge of Java or Kotlin',
          'Understanding of Android SDK and development tools',
          'Willingness to learn and grow in a team environment',
        ],
        preferredSkills: [
          'Familiarity with RESTful APIs',
          'Good communication skills',
          'Basic understanding of mobile UI/UX principles',
        ],
        productDesigner:
          'Collaborate with senior developers to improve application features.',
        expirationDate: '2024-12-31',
        phone: '+91-234-567-8910',
        email: 'jobs@appinspire.com',
        salary: '50,000/Month',
        companyLogo: 'assets/images/jobs/job-34.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 43,
        title: 'Junior Full-Stack Developer',
        company: 'WebSync Technologies',
        location: 'Germany',
        type: 'Full time',
        posted: '30 mins ago',
        about: [
          'WebSync Technologies is a global technology company specializing in full-stack web development.',
          'We focus on delivering high-quality web applications that are secure, scalable, and user-friendly.',
          'Our team is passionate about using the latest technologies to build software that meets client needs and expectations.',
          'At WebSync Technologies, we encourage creative problem-solving, teamwork, and the continuous development of our developers.',
        ],
        description:
          'Work on both client-side and server-side code, focusing on JavaScript and PHP development.',
        jobDescriptionInfo:
          'Develop web applications by integrating front-end and back-end technologies.',
        requirements: [
          'Familiarity with JavaScript and PHP',
          'Basic understanding of databases (MySQL, MongoDB)',
          'Willingness to learn and adapt to new technologies',
        ],
        preferredSkills: [
          'Experience with front-end frameworks (React, Vue)',
          'Good problem-solving skills',
          'Ability to work in a team environment',
        ],
        productDesigner:
          'Collaborate with designers to create user-friendly applications.',
        expirationDate: '2024-12-31',
        phone: '+49-234-567-8911',
        email: 'careers@websynctech.com',
        salary: '€42,000/year',
        companyLogo: 'assets/images/jobs/job-35.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 44,
        title: 'Junior Software Engineer (Remote)',
        company: 'Innovatech Solutions',
        location: 'Remote',
        type: 'Full time',
        posted: '3 mins ago',
        about: [
          'Innovatech Solutions is a forward-thinking technology company specializing in software development and innovation.',
          'We aim to create high-impact software solutions that solve complex challenges for businesses worldwide.',
          'Our teams are dedicated to continuous learning and developing software with the latest technologies.',
          'At Innovatech Solutions, we foster a culture of collaboration and value creative approaches to problem-solving.',
        ],
        description:
          'Collaborate with a global team to develop software applications in a fast-paced environment.',
        jobDescriptionInfo:
          'Contribute to software development projects and participate in code reviews.',
        requirements: [
          'Basic knowledge of programming languages (Java, C#, Python)',
          'Understanding of software development methodologies',
          'Ability to work collaboratively in a team',
        ],
        preferredSkills: [
          'Experience with version control (Git)',
          'Strong analytical skills',
          'Good communication skills',
        ],
        productDesigner:
          'Work with cross-functional teams to deliver high-quality software.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8912',
        email: 'jobs@innovatech.com',
        salary: '$55,000/year',
        companyLogo: 'assets/images/jobs/job-36.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 45,
        title: 'Software Developer Intern',
        company: 'CodeCraft Labs',
        location: 'Remote',
        type: 'Part time',
        posted: '22 mins ago',
        about: [
          'CodeCraft Labs is a technology innovation hub, focused on creating impactful software solutions for clients globally.',
          'We provide our interns with an opportunity to work alongside experienced developers and contribute to real-world projects.',
          'Our team promotes growth, learning, and exposure to the latest tools and technologies in the development space.',
          'At CodeCraft Labs, we value collaboration and the creative input of all team members.',
        ],
        description:
          'Assist in developing web applications, working with front-end and back-end teams to deliver features.',
        jobDescriptionInfo:
          'Gain hands-on experience in software development and project collaboration.',
        requirements: [
          'Basic knowledge of web technologies (HTML, CSS, JavaScript)',
          'Willingness to learn new programming languages',
          'Ability to work in a team environment',
        ],
        preferredSkills: [
          'Familiarity with Git version control',
          'Strong communication skills',
          'Good time management skills',
        ],
        productDesigner:
          'Collaborate with senior developers to deliver project features.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8913',
        email: 'careers@codecraftlabs.com',
        salary: ' $30,000/Month',
        companyLogo: 'assets/images/jobs/job-37.png',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 46,
        title: 'Junior Mobile App Developer',
        company: 'AppTrail',
        location: 'Remote',
        type: 'Freelance',
        posted: '4 days ago',
        about: [
          'AppTrail is a remote-first company specializing in mobile application development for iOS and Android platforms.',
          'We focus on building user-friendly apps that deliver high performance and an intuitive experience.',
          'Our team works remotely, offering a collaborative and flexible environment to foster creativity.',
          'At AppTrail, we value independence, innovation, and the pursuit of excellence in every project we undertake.',
        ],
        description:
          'Develop mobile apps for iOS and Android using Java and Swift.',
        jobDescriptionInfo:
          'Create and maintain mobile applications for various clients.',
        requirements: [
          'Basic knowledge of Java and Swift',
          'Understanding of mobile app development lifecycle',
          'Ability to work independently',
        ],
        preferredSkills: [
          'Familiarity with mobile UI/UX design principles',
          'Good problem-solving skills',
          'Ability to manage multiple projects',
        ],
        productDesigner:
          'Collaborate with clients to meet their app development needs.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8914',
        email: 'jobs@apptrail.com',
        salary: '$28,000/Month',
        companyLogo: 'assets/images/jobs/job-38.png',
        urgent: true,
        senior: false,
        fullTime: false,
      },
      {
        id: 47,
        title: 'Full-Stack Developer (Junior)',
        company: 'SkyTech Solutions',
        location: 'New York, NY',
        type: 'Full time',
        posted: '30 sec ago',
        about: [
          'SkyTech Solutions is a dynamic technology company focused on delivering innovative software solutions for businesses.',
          'We specialize in developing scalable, high-performance applications using modern technologies.',
          'Our team thrives on collaboration, creativity, and a passion for building robust solutions.',
          'At SkyTech Solutions, we believe in empowering our developers to grow and innovate in a supportive and collaborative environment.',
        ],
        description:
          'Work on both client and server-side development, using JavaScript and ',
        jobDescriptionInfo:
          'Contribute to full-stack web development projects, ensuring seamless integration.',
        requirements: [
          'Familiarity with JavaScript and Python',
          'Basic understanding of front-end frameworks (React, Angular)',
          'Willingness to learn new technologies',
        ],
        preferredSkills: [
          'Experience with RESTful APIs',
          'Strong problem-solving skills',
          'Ability to work collaboratively',
        ],
        productDesigner:
          'Collaborate with the design team to enhance user interfaces.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8915',
        email: 'careers@skytechsolutions.com',
        salary: '$58,000/year',
        companyLogo: 'assets/images/jobs/job-39.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 48,
        title: 'Junior DevOps Engineer',
        company: 'Cloudify Tech',
        location: 'Remote',
        type: 'Full time',
        posted: '52 mins ago',
        about: [
          'CloudMinds Technologies is a cutting-edge company focused on cloud computing and automation solutions.',
          'We specialize in creating reliable, scalable, and secure cloud-based services for businesses.',
          'Our team values continuous learning, collaboration, and the application of automation to improve system efficiency.',
          'At CloudMinds, we encourage innovation and provide opportunities for professional growth in the field of cloud computing.',
        ],
        description:
          'Assist in managing and automating infrastructure and deployment pipelines.',
        jobDescriptionInfo:
          'Support the DevOps team in implementing CI/CD practices and infrastructure automation.',
        requirements: [
          'Basic knowledge of DevOps tools (Docker, Jenkins)',
          'Understanding of cloud platforms (AWS, Azure)',
          'Willingness to learn and grow in a fast-paced environment',
        ],
        preferredSkills: [
          'Strong analytical and problem-solving skills',
          'Good communication skills',
          'Ability to work in a team',
        ],
        productDesigner:
          'Collaborate with software engineers to improve deployment processes.',
        expirationDate: '2024-12-31',
        phone: '+1-234-567-8916',
        email: 'jobs@cloudifytech.com',
        salary: '$52,000/Month',
        companyLogo: 'assets/images/jobs/job-40.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 49,
        title: 'Back-End Software Engineer',
        company: 'DataFlow Solutions',
        location: 'London',
        type: 'Full time',
        posted: '3 days ago',
        about: [
          'DataFlow Solutions is a global leader in delivering cutting-edge data management and software solutions.',
          'We specialize in creating robust, scalable back-end infrastructure for complex systems.',
          'Our team is focused on building reliable, high-performance systems that power modern applications.',
          'At DataFlow Solutions, we value innovation, collaboration, and continuous learning to help our engineers grow and thrive.',
        ],
        description:
          'Build and maintain the back-end infrastructure using Node.js and Python',
        jobDescriptionInfo:
          'Develop server-side logic and ensure high performance of applications.',
        requirements: [
          'Familiarity with Node.js and Python',
          'Basic understanding of database systems (MySQL, MongoDB)',
          'Willingness to learn and adapt to new technologies',
        ],
        preferredSkills: [
          'Experience with RESTful APIs',
          'Strong problem-solving skills',
          'Good communication skills',
        ],
        productDesigner:
          'Collaborate with front-end developers to deliver full-stack solutions.',
        expirationDate: '2024-12-31',
        phone: '+44-234-567-8917',
        email: 'jobs@dataflowsolutions.com',
        salary: '£42,000/year',
        companyLogo: 'assets/images/jobs/job-41.png',
        urgent: true,
        senior: false,
        fullTime: true,
      },
      {
        id: 50,
        title: 'Front-End Developer (Entry-level)',
        company: 'PixelPoint Studios',
        location: 'Cairo',
        type: 'Part time',
        posted: '22 mins ago',
        about: [
          'PixelPoint Studios is a creative agency that specializes in designing innovative digital experiences.',
          'We focus on building responsive and engaging user interfaces that delight users.',
          'Our team works closely with designers and developers to create visually stunning web applications.',
          'At PixelPoint Studios, we encourage creativity and foster a collaborative work culture where learning and growth are key priorities.',
        ],
        description:
          'Build and optimize web interfaces using React and CSS for improved user experiences.',
        jobDescriptionInfo:
          'Enhance the user interface of web applications to ensure a seamless user experience.',
        requirements: [
          'Basic knowledge of HTML, CSS, and JavaScript',
          'Familiarity with React framework',
          'Willingness to learn and improve skills',
        ],
        preferredSkills: [
          'Good problem-solving skills',
          'Ability to work in a team environment',
          'Strong attention to detail',
        ],
        productDesigner:
          'Work closely with UI/UX designers to implement visual designs.',
        expirationDate: '2024-12-31',
        phone: '+20-234-567-8918',
        email: 'careers@pixelpointstudios.com',
        salary: '$29,000/Month',
        companyLogo: 'assets/images/jobs/job-42.png',
        urgent: true,
        senior: false,
        fullTime: false,
      },
    ];
  }
  getRandomJobs(): any[] {
    const jobs = this.getJobs();
    // Shuffle the jobs array
    const shuffledJobs = jobs.sort(() => 0.5 - Math.random());
    // Return the first five jobs from the shuffled array
    return shuffledJobs.slice(0, 5);
  }
}
