import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class CompanyListesService {
  constructor() {}
  getCompanies() {
    return [
      {
        id: 1,
        title: 'Front-End Developer',
        company: 'VOIS-Code',
        location: 'Cairo',
        companyLogo: 'assets/images/Home/Company-1.jpg',
        category: 'Software',
      },
      {
        id: 2,
        title: 'Fresh (React Native) Developer',
        company: 'Capgemini',
        companyLogo: 'assets/images/Home/Company-2.jpg',
        location: 'Canada',
        category: 'Software',
      },
      {
        id: 3,
        title: 'FullStack Senior Software Engineer (Ruby/JS-TS)',
        company: 'Procore Technologies',
        companyLogo: 'assets/images/Home/Company-3.jpg',
        location: 'India',
        category: 'Software',
      },
      {
        id: 4,
        title: 'Junior Frontend Developer (Angular)',
        company: 'Emaratech',
        companyLogo: 'assets/images/Home/Company-4.jpg',
        location: 'Cairo',
        category: 'Software',
      },
      {
        id: 5,
        title: 'Fresh Backend (.Net)',
        company: 'Santionan',
        companyLogo: 'assets/images/Home/Company-5.jpg',
        location: 'Cairo',
        category: 'Software',
      },
      {
        id: 6,
        title: 'Junior Web Developer (Remote)',
        company: 'Cocharge',
        companyLogo: 'assets/images/Home/Company-6.jpg',
        location: 'Germany',
        category: 'Software',
      },
      {
        id: 7,
        title: 'Senior React Native Developer',
        company: 'Gucci, Inc',
        companyLogo: 'assets/images/Home/Company-7.jpg',
        location: 'New York',
        category: 'Software',
      },
      {
        id: 8,
        title: 'SW QA Engineer - RVE',
        company: 'Siemens Software',
        companyLogo: 'assets/images/Home/Company-8.jpg',
        location: 'Remote',
        category: 'Software',
      },
      {
        id: 9,
        title: 'Junior Front-End Developer',
        company: 'TechSphere',
        companyLogo: 'assets/images/jobs/job-1.png',
        location: 'New York',
        category: 'Software',
      },
      {
        id: 10,
        title: 'Junior Back-End Developer',
        company: 'CodeNexus Ltd',
        companyLogo: 'assets/images/jobs/job-2.png',
        location: 'London, UK',
        category: 'Software',
      },
      {
        id: 11,
        title: 'Junior UI/UX Designer',
        company: 'DesignWaves',
        companyLogo: 'assets/images/jobs/job-3.png',
        location: 'Remote',
        category: 'Designer',
      },
      {
        id: 12,
        title: 'Junior Full-Stack Developer',
        company: 'CloudMinds Technologies',
        location: 'Canada',
        companyLogo: 'assets/images/jobs/job-4.png',
        category: 'Software',
      },
      {
        id: 13,
        title: 'Junior Front-End Developer',
        company: 'PixelTech',
        location: 'Berlin',
        companyLogo: 'assets/images/jobs/job-5.png',
        category: 'Software',
      },
      {
        id: 14,
        title: 'Junior Back-End Engineer',
        company: 'Skyline Software',
        location: 'Austin, USA',
        companyLogo: 'assets/images/jobs/job-6.png',
        category: 'Software',
      },
      {
        id: 15,
        title: 'UI/UX Designer',
        company: 'BrightPixel Studios',
        location: 'Cairo',
        companyLogo: 'assets/images/jobs/job-7.png',
        category: 'Designer',
      },
      {
        id: 16,
        title: 'Junior Front-End Developer',
        company: 'InnovateTech',
        location: 'SanFrancisco',
        companyLogo: 'assets/images/jobs/job-8.png',
        category: 'Software',
      },
      {
        id: 17,
        title: 'Back-End Developer',
        company: 'DataBridge Systems',
        location: 'Cairo',
        companyLogo: 'assets/images/jobs/job-9.png',
        category: 'Software',
      },
      {
        id: 18,
        title: 'Junior UI Designer',
        company: 'CreativeCode Studios',
        location: 'Remote',
        companyLogo: 'assets/images/jobs/job-10.png',
        category: 'Designer',
      },
      {
        id: 19,
        title: 'Junior Front-End Developer (React)',
        company: 'PixelHub',
        location: 'New York',
        companyLogo: 'assets/images/jobs/job-11.png',
        category: 'Software',
      },
      {
        id: 20,
        title: 'Junior Back-End Developer',
        company: 'CodeForge',
        location: 'London, UK',
        companyLogo: 'assets/images/jobs/job-12.png',
        category: 'Software',
      },
      {
        id: 21,
        title: 'Junior Flutter Developer',
        company: 'AppX Innovations',
        location: 'Canada',
        companyLogo: 'assets/images/jobs/job-13.png',
        category: 'Software',
      },
      {
        id: 22,
        title: 'Full-Stack Developer (Flutter/Node.js)',
        company: 'CloudStack',
        location: 'SanFrancisco',
        companyLogo: 'assets/images/jobs/job-43.png',
        category: 'Software',
      },
      {
        id: 23,
        title: 'Junior Flutter Developer',
        company: 'TechNest',
        location: 'Germany',
        companyLogo: 'assets/images/jobs/job-28.png',
        category: 'Software',
      },
      {
        id: 24,
        title: 'Junior Back-End Developer (Python)',
        company: 'DataWave',
        location: 'India',
        companyLogo: 'assets/images/jobs/job-16.png',
        category: 'Software',
      },
      {
        id: 25,
        company: 'WebMinds',
        companyLogo: 'assets/images/jobs/job-17.png',
        location: 'Cairo',
        title: 'Junior Front-End Developer (Angular)',
        category: 'Software',
      },
      {
        id: 26,
        company: 'MobileX',
        companyLogo: 'assets/images/jobs/job-18.png',
        location: 'Cairo',
        title: 'Junior Flutter Developer',
        category: 'Software',
      },
      {
        id: 27,
        company: 'NextGen Innovations',
        companyLogo: 'assets/images/jobs/job-19.png',
        location: 'New York, NY',
        title: 'Junior Software Engineer (Full-Stack)',
        category: 'Software',
      },
      {
        id: 28,
        company: 'CodeSphere',
        companyLogo: 'assets/images/jobs/job-20.png',
        location: 'Canada',
        title: 'Junior Front-End Developer (Vue.js)',
        category: 'Software',
      },
      {
        id: 29,
        company: 'WebForge',
        companyLogo: 'assets/images/jobs/job-21.png',
        location: 'Freelance',
        title: 'Junior Front-End Developer (React)',
        category: 'Software',
      },
      {
        id: 30,
        company: 'TechNova',
        companyLogo: 'assets/images/jobs/job-22.png',
        location: 'Remote',
        title: 'Junior Software Engineer (JavaScript)',
        category: 'Software',
      },
      {
        id: 31,
        company: 'GFlutterWorks',
        companyLogo: 'assets/images/jobs/job-23.png',
        location: 'Remote',
        title: 'Junior Flutter Developer',
        category: 'Software',
      },
      {
        id: 32,
        company: 'DevLink Technologies',
        companyLogo: 'assets/images/jobs/job-24.png',
        location: 'Remote',
        title: 'Junior Flutter Developer',
        category: 'Software',
      },
      {
        id: 33,
        company: 'AppTide Solutions',
        companyLogo: 'assets/images/jobs/job-25.png',
        location: 'Freelance',
        title: 'Junior Flutter Developer',
        category: 'Software',
      },
      {
        id: 34,
        company: 'InnoWave',
        companyLogo: 'assets/images/jobs/job-26.png',
        location: 'Germany',
        title: 'Software Engineer Intern',
        category: 'Software',
      },
      {
        id: 35,
        company: 'CloudNet Technologies',
        companyLogo: 'assets/images/jobs/job-27.png',
        location: 'Remote',
        title: 'Junior DevOps Engineer',
        category: 'Software',
      },
      {
        id: 36,
        company: 'UIX Solutions',
        companyLogo: 'assets/images/jobs/job-28.png',
        location: 'Cairo',
        title: 'Front-End Developer',
        category: 'Software',
      },
      {
        id: 37,
        company: 'CodeBlitz',
        companyLogo: 'assets/images/jobs/job-29.png',
        location: 'New York',
        title: 'Mobile App Developer (Flutter)',
        category: 'Software',
      },
      {
        id: 38,
        company: 'CodeBridge Solutions',
        companyLogo: 'assets/images/jobs/job-30.png',
        location: 'Remote',
        title: 'Junior Software Engineer',
        category: 'Software',
      },
      {
        id: 39,
        title: 'Junior Software Engineer (Remote)',
        company: 'NextGen Technologies',
        location: 'Remote',
        companyLogo: 'assets/images/jobs/job-31.png',
        category: 'Software',
      },
      {
        id: 40,
        title: 'Junior Flutter Developer (Remote)',
        company: 'AppGlobe',
        location: 'Remote',
        companyLogo: 'assets/images/jobs/job-32.png',
        category: 'Software',
      },
      {
        id: 41,
        title: 'Backend Developer (Junior)',
        company: 'DataFlow Solutions',
        location: 'Canada',
        companyLogo: 'assets/images/jobs/job-33.png',
        category: 'Software',
      },
      {
        id: 42,
        title: 'Entry-Level Mobile App Developer',
        company: 'AppInspire',
        location: 'India',
        companyLogo: 'assets/images/jobs/job-34.png',
        category: 'Software',
      },
      {
        id: 43,
        title: 'Junior Full-Stack Developer',
        company: 'WebSync Technologies',
        location: 'Germany',
        companyLogo: 'assets/images/jobs/job-35.png',
        category: 'Software',
      },
      {
        id: 44,
        title: 'Junior Software Engineer (Remote)',
        company: 'Innovatech Solutions',
        location: 'Remote',
        companyLogo: 'assets/images/jobs/job-36.png',
        category: 'Software',
      },
      {
        id: 45,
        title: 'Software Developer Intern',
        company: 'CodeCraft Labs',
        location: 'Remote',
        companyLogo: 'assets/images/jobs/job-37.png',
        category: 'Software',
      },
      {
        id: 46,
        title: 'Junior Mobile App Developer',
        company: 'AppTrail',
        location: 'Remote',
        companyLogo: 'assets/images/jobs/job-38.png',
        category: 'Software',
      },
      {
        id: 47,
        title: 'Full-Stack Developer (Junior)',
        company: 'SkyTech Solutions',
        location: 'New York',
        companyLogo: 'assets/images/jobs/job-39.png',
        category: 'Software',
      },
      {
        id: 48,
        title: 'Junior DevOps Engineer',
        company: 'Cloudify Tech',
        location: 'Remote',
        companyLogo: 'assets/images/jobs/job-40.png',
        category: 'Software',
      },
      {
        id: 49,
        title: 'Back-End Software Engineer',
        company: 'DataFlow Solutions',
        location: 'London',
        companyLogo: 'assets/images/jobs/job-41.png',
        category: 'Software',
      },
      {
        id: 50,
        title: 'Front-End Developer (Entry-level)',
        company: 'PixelPoint Studios',
        location: 'Cairo',
        companyLogo: 'assets/images/jobs/job-42.png',
        category: 'Software',
      },
    ];
  }
  getRandomJobs(): any[] {
    const companies = this.getCompanies();
    // Shuffle the jobs array
    const shuffledCompanies = companies.sort(() => 0.5 - Math.random());
    // Return the first five jobs from the shuffled array
    return shuffledCompanies.slice(0, 5);
  }
}
